Build namespace-only bisect images

diff --git a/.github/workflows/build_kernel.yml b/.github/workflows/build_kernel.yml
--- a/.github/workflows/build_kernel.yml
+++ b/.github/workflows/build_kernel.yml
@@ -91,12 +91,15 @@ jobs:
         export ARCH=arm64
         export SUBARCH=arm64
         make $KERNEL_CMDLINE Pangu_KSU_defconfig
+        for option in SYSVIPC POSIX_MQUEUE FHANDLE NAMESPACES UTS_NS IPC_NS PID_NS NET_NS; do
+          grep -q "^CONFIG_${option}=y$" out/.config || { echo "Missing CONFIG_${option}=y"; exit 1; }
+        done
         make $KERNEL_CMDLINE -j$(nproc --all)
-        tools/mkbootimg --kernel out/arch/arm64/boot/Image.gz --base 0x0 --cmdline "loglevel=4 initcall_debug=n page_tracker=on slub_min_objects=16 unmovable_isolate1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=enforcing buildvariant=user" --tags_offset 0x07A00000 --kernel_offset 0x00080000 --ramdisk_offset 0x07c00000 --header_version 1 --os_version 9 --os_patch_level 2020-09-05  --output Pangu_V9_KSU-enforcing-${{ steps.get_time.outputs.TIME }}.img
-        tools/mkbootimg --kernel out/arch/arm64/boot/Image.gz --base 0x0 --cmdline "loglevel=4 initcall_debug=n page_tracker=on slub_min_objects=16 unmovable_isolate1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=permissive buildvariant=user" --tags_offset 0x07A00000 --kernel_offset 0x00080000 --ramdisk_offset 0x07c00000 --header_version 1 --os_version 9 --os_patch_level 2020-09-05  --output Pangu_V9_KSU-permissive-${{ steps.get_time.outputs.TIME }}.img
+        tools/mkbootimg --kernel out/arch/arm64/boot/Image.gz --base 0x0 --cmdline "loglevel=4 initcall_debug=n page_tracker=on slub_min_objects=16 unmovable_isolate1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=enforcing buildvariant=user" --tags_offset 0x07A00000 --kernel_offset 0x00080000 --ramdisk_offset 0x07c00000 --header_version 1 --os_version 9 --os_patch_level 2020-09-05  --output Pangu_V9_KSU-BisectNS-enforcing-${{ steps.get_time.outputs.TIME }}.img
+        tools/mkbootimg --kernel out/arch/arm64/boot/Image.gz --base 0x0 --cmdline "loglevel=4 initcall_debug=n page_tracker=on slub_min_objects=16 unmovable_isolate1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=permissive buildvariant=user" --tags_offset 0x07A00000 --kernel_offset 0x00080000 --ramdisk_offset 0x07c00000 --header_version 1 --os_version 9 --os_patch_level 2020-09-05  --output Pangu_V9_KSU-BisectNS-permissive-${{ steps.get_time.outputs.TIME }}.img
 
     - name: Upload V9-KSU-Kernel
       uses: actions/upload-artifact@v4
       with:
-        name: Pangu_V9_KSU-kernel-${{ steps.get_time.outputs.TIME }}
+        name: Pangu_V9_KSU-BisectNS-kernel-${{ steps.get_time.outputs.TIME }}
         path: "Pangu_V9_KSU-*.img"
